import Phaser from 'phaser';
import { BootScene } from './scenes/BootScene';
import { MenuScene } from './scenes/MenuScene';
import { LevelSelectScene } from './scenes/LevelSelectScene';
import { GalleryScene } from './scenes/GalleryScene';
import { GameScene } from './scenes/GameScene';
import { BASE_HEIGHT, BASE_WIDTH, theme } from './render/Theme';
import { renderShareCard } from './render/ShareCard';
import { playIntro } from './render/Intro';
import { Ads } from './systems/Ads';

/*
 * Start the opening film immediately, and do NOT await it. The game is built
 * behind it on the next line, so by the time the film ends the menu is already
 * there — the five seconds are spent loading rather than instead of loading.
 *
 * The banner is held for the duration. It is a NATIVE view above the webview,
 * so nothing the page draws can cover it; without the hold it slides in over
 * the film. Scenes keep calling showBanner() as they always did — the want is
 * remembered and honoured the moment the film clears.
 */
void (async () => {
  Ads.holdBanner();
  await playIntro();
  void Ads.releaseBanner();
})();

const game = new Phaser.Game({
  type: Phaser.AUTO,
  parent: 'app',
  // Matching the page background means FIT's letterbox bars are invisible —
  // the paper simply runs to the edge of whatever screen it lands on.
  backgroundColor: theme().paper,
  scale: {
    mode: Phaser.Scale.FIT,
    autoCenter: Phaser.Scale.CENTER_BOTH,
    width: BASE_WIDTH,
    height: BASE_HEIGHT,
  },
  /*
   * Phaser allocates one touch Pointer by default, so a second finger anywhere
   * on the glass is dropped entirely. That breaks the fast-retry path this game
   * is built around: a collision always happens mid-drag, so the drawing finger
   * is still down during the 400ms flash, and reaching in with the other hand
   * to restart would find no Pointer free. Three covers a stray palm too.
   */
  input: { activePointers: 3 },
  render: {
    antialias: true,
    roundPixels: false,
    powerPreference: 'high-performance',
  },
  fps: { target: 60 },
  scene: [BootScene, MenuScene, LevelSelectScene, GalleryScene, GameScene],
});

/*
 * Force the ScaleManager to recompute the canvas bounds — which drive pointer
 * mapping — whenever the real viewport changes. Inside a Capacitor webview the
 * size settles AFTER the game is created (status bar, safe areas, splash
 * dismissal) and often without firing a window 'resize'. A stale canvas rect
 * puts every touch a few points away from where the player aimed, and in a game
 * that is nothing but a drawn line, a few points is the whole experience.
 */
const refresh = (): void => {
  game.scale.refresh();
};
window.addEventListener('resize', refresh);
window.addEventListener('orientationchange', refresh);
window.visualViewport?.addEventListener('resize', refresh);
window.visualViewport?.addEventListener('scroll', refresh);
for (const ms of [50, 250, 600, 1200]) setTimeout(refresh, ms);

// Dev-only handle for tooling. `import.meta.env.DEV` is a compile-time
// constant, false in `vite build`, so this is tree-shaken out of the bundle.
if (import.meta.env.DEV) {
  const w = window as unknown as {
    game: Phaser.Game;
    foldwing: { renderShareCard: typeof renderShareCard };
  };
  w.game = game;
  // Asset tooling hook: the app icon is generated by asking the game to draw a
  // figure, so the mark on the home screen is literally made of the mechanic.
  w.foldwing = { renderShareCard };
}
